services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: devstreak
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  web:
    build: .
    # ensures the container runs in /app
    working_dir: /app
    # runs the CMD from Dockerfile if you omit this
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"    # host:container
    depends_on:
      - db
    env_file:
      - .env

volumes:
  db_data:
