services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: devstreak
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  web:
    build: .
    # ensures the container runs in /app
    working_dir: /app
    # runs the CMD from Dockerfile if you omit this
    command: daphne -b 0.0.0.0 -p 8000 backend.asgi:application
    volumes:
      - .:/app
    ports:
      - "8000:8000"    # host:container
    depends_on:
      - db
      - redis
    env_file:
      - .env
    environment:
      - DJANGO_SETTINGS_MODULE=backend.settings

  worker:
    build: .
    working_dir: /app
    command: celery -A backend worker --beat --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    env_file:
      - .env
    environment:
      - DJANGO_SETTINGS_MODULE=backend.settings

volumes:
  db_data:
